### ISSUE TITLE
Serializer question not covered in rails-api lesson

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/rails-api-diagnostic#33]
Since the focus of the rails-api code-along portion is to execute the commands to create a new rails-api, without much explanation,  the serializer benefits question in the diagnostic should either be removed or the rails-api lesson should incorporate more explanation on topics covered in the diagnostic.

**Comment by jrhorn424** [comment]
Was this tracked also over at the lesson? If so, this issue should be cross referenced.

**Comment by payne-chris-r** [comment]
Did we kill the question?

**Comment by BenGitsCode** [comment]
The question has been removed. This seems bordering on a duplicate of #83

**Comment by gaand** [comment]
Which talk is this referencing?

**Comment by BenGitsCode** [comment]
I think it was referencing https://github.com/ga-wdi-boston/rails-api

**Comment by jrhorn424** [comment]
This is covered now. I'm still ok with removing it.

**Comment by gaand** [comment]
Are we asking a question about serializers somewhere?

And, what was the question that's been removed?

**Comment by jrhorn424** [comment]
We are asking a question about serializers in `rails-api-single-resource-diagnostic`.

I cannot find a question about serializers in recent history of `diagnostic.md` (four cohorts or so). My best guess is that this issue is old, or was filed on the wrong repository.

It could be a holdover from when this repo was both `rails-api-diagnostic` and `rails-api-single-resource-diagnostic`.
